version: '3.8'

volumes:
  copaw-data:
    name: copaw-data
  copaw-secrets:
    name: copaw-secrets

services:
  copaw:
    image: agentscope/copaw:latest
    container_name: copaw
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - COPAW_AUTH_ENABLED=true
    #   - COPAW_AUTH_USERNAME=admin
    #   - COPAW_AUTH_PASSWORD=yourpassword
    #   - COPAW_ENABLE_BUILTIN_QA_AGENT=false
    volumes:
      - copaw-data:/app/working
      - copaw-secrets:/app/working.secret
