# -*- coding: utf-8 -*-
"""Minimal recruitment job helpers."""

from .external_models import (
    ExternalJobLink,
    ExternalJobLinkView,
    ExternalJobLinksFile,
    RecruitPlatformAccount,
    RecruitPlatformAccountsFile,
)
from .external_service import list_job_external_links
from .external_service import (
    ExternalJobLinkConflictError,
    ExternalJobLinkNotFoundError,
    PlatformAccountNotFoundError,
    ensure_platform_account,
    unlink_job_external_link,
    upsert_job_external_link,
)
from .models import (
    BindJobToChatRequest,
    CreateJobFromChatRequest,
    DeleteJobResult,
    JobSpec,
    JobsFile,
)
from .pipeline_models import (
    AddPipelineCandidateRequest,
    BatchAddPipelineCandidatesRequest,
    BatchPipelineEntryMutationResult,
    CandidateProfile,
    CandidateProfileInput,
    JobPipelineView,
    PipelineActivity,
    PipelineEntry,
    PipelineEntryMutationResult,
    PipelineEntryView,
    PipelineStageDefinition,
    UpdatePipelineEntryAssessmentRequest,
    UpdatePipelineEntryStageRequest,
)
from .pipeline_service import (
    add_candidate_to_job_pipeline,
    add_candidates_to_job_pipeline,
    list_job_pipeline,
    update_pipeline_entry_assessment,
    update_pipeline_entry_stage,
)
from .service import (
    JobAmbiguousError,
    JobAlreadyBoundError,
    JobChatNotFoundError,
    JobNotFoundError,
    bind_job_to_chat,
    create_job_from_chat,
    delete_job,
    get_job,
    job_binding_from_chat,
    list_jobs,
)

__all__ = [
    "BindJobToChatRequest",
    "CreateJobFromChatRequest",
    "DeleteJobResult",
    "ExternalJobLink",
    "ExternalJobLinksFile",
    "ExternalJobLinkView",
    "JobSpec",
    "JobsFile",
    "RecruitPlatformAccount",
    "RecruitPlatformAccountsFile",
    "PlatformAccountNotFoundError",
    "ExternalJobLinkConflictError",
    "ExternalJobLinkNotFoundError",
    "AddPipelineCandidateRequest",
    "BatchAddPipelineCandidatesRequest",
    "BatchPipelineEntryMutationResult",
    "CandidateProfile",
    "CandidateProfileInput",
    "JobPipelineView",
    "PipelineActivity",
    "PipelineEntry",
    "PipelineEntryMutationResult",
    "PipelineEntryView",
    "PipelineStageDefinition",
    "UpdatePipelineEntryAssessmentRequest",
    "UpdatePipelineEntryStageRequest",
    "JobAmbiguousError",
    "JobAlreadyBoundError",
    "JobChatNotFoundError",
    "JobNotFoundError",
    "bind_job_to_chat",
    "create_job_from_chat",
    "delete_job",
    "list_jobs",
    "get_job",
    "job_binding_from_chat",
    "list_job_external_links",
    "ensure_platform_account",
    "unlink_job_external_link",
    "upsert_job_external_link",
    "add_candidate_to_job_pipeline",
    "add_candidates_to_job_pipeline",
    "list_job_pipeline",
    "update_pipeline_entry_assessment",
    "update_pipeline_entry_stage",
]
